apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJVMkZ0YjJsc2IyWm1PVEE2WjJod1h6RXlNamh3YlhocGVrRmFRa0ZIVlZnNGIxazFURGxOYVZGWmJ6TkdlakkwY3pSWmJRPT0iCiAgICB9CiAgfQp9
