apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2Ftb2lsb2ZmOTAiLCJwYXNzd29yZCI6ImdocF9SZ250TWJMcGQ3ZmhzS1VQbFl5clFPTmxXVG1tcUkyUzZEY3AiLCJhdXRoIjoiYzJGdGIybHNiMlptT1RBNloyaHdYMUpuYm5STllreHdaRGRtYUhOTFZWQnNXWGx5VVU5T2JGZFViVzF4U1RKVE5rUmpjQT09In19fQ==